### ISSUE TITLE
compile errors

### ISSUE THREAD

**Issue by netpipe** [MurphyMc/antsy#6]
lilt.c:818:10: error: ‘TMT_MSG_TITLE’ undeclared (first use in this function);

lilt.c:829:10: error: ‘TMT_MSG_SETMODE’ undeclared (first use in this function);

lilt.c:830:10: error: ‘TMT_MSG_UNSETMODE’ undeclared (first use in this function);

**Comment by netpipe** [comment]
nm found your port

**Comment by MurphyMc** [comment]
For those playing along at home, these should work if you use my fork of libtmt: https://github.com/MurphyMc/libtmt

Without that, you should be able to get it to compile by switching off the "Allow xterm window title setting" and "libtmt has TMT_MSG_(UN)SETMODE" options in cmake.

**Comment by netpipe** [comment]
I'm going to be using this to fixup 8086tiny emulator, already have it ported to tmt just need the sdl part working which is being freelanced currently based on your code.  https://github.com/netpipe/IrrlichtDemos/tree/master/Apps/irr8086tiny
